name: AutoRio
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: pip install requests
      - run: python grab.py
      - name: Push
        run: |
          git config --global user.name "ManhDZ"
          git config --global user.email "manh@dz.com"
          git add live.m3u
          git commit -m "Update link" || exit 0
          git push
