name: AutoRio
on:
  schedule:
    - cron: '*/5 * * * *' # Tôi để 5 phút cho an toàn nhé
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    # Dòng này là chìa khóa để phá lỗi 128 đây:
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: pip install requests
      - run: python grab.py
      - name: Push
        run: |
          git config --global user.name "feeltherain77"
          git config --global user.email "feeltherain77@users.noreply.github.com"
          git add live.m3u
          git commit -m "Update" || exit 0
          git push
